### ISSUE TITLE
jump list loses > marker

### ISSUE THREAD

**Issue by Konfekt** [inkarkat/vim-EnhancedJumps#6]
**Describe the bug**

Error messages

```vim
Error detected while processing function EnhancedJumps#Go[5]..EnhancedJumps#Common#SliceJumpsInDirection[16]..<SNR>438_GetCurrentIndex[13]..function EnhancedJumps#Go[5]..EnhancedJumps#Common#SliceJumpsInDirection[16]..<SNR>438_GetCurrentIndex:
line   13:
E605: Exception not caught: EnhancedJumps: jump list does not contain > marker
```

Indeed, `:jumps` shows that the `>` marker disappeared.

**How to Reproduce**

Install vim-EnhancedJumps, restart Vim, hit `<c-o>` to jump back in jump list and then `<c-i>` to jump forward. 

**Expected Behavior**

Message that the end of jump list was attained.

**Environment**

 - Plugin version: Commit 84df0d73f732bfb926763f5b0469a47dd63289a1
 
- Dependency versions:
  ingo-library plugin : commit 21b6ea4f7ec964502ec7462ceaaaf2b912355d24

 - Vim version : 

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 22 2021 19:31:05)
Included patches: 1-3582
Compiled by <https://www.msys2.org/>

and

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan  4 2022 23:02:36)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-4005

 - OS: 

Edition	Windows 10 Pro
Version	21H2
Build 19044.1586

 - Install method:  vim-plug

**Comment by inkarkat** [comment]
If I remember correctly, I've run into this exception once, but it's been a long time ago. I update to the latest development build every few weeks (currently at Vim 8.2.4136). I've tried to reproduce the problem, also with a clean viminfo (`vim -i /tmp/new`), but failed in that. Does this occur regularly for you, or just occasionally / under special conditions (like clearing your _viminfo_ file)?

Reading [`:help jumplist`](https://vimhelp.appspot.com/motion.txt.html#jumplist), a missing `>` indicator is not mentioned. So the plugin treats this as unspecified behavior and refuses to work (rather than making assumptions that could be wrong). Unless the problem happens a lot for you, I'd rather keep it that way.

---

On my todo list for the plugin is moving to the [`getjumplist()`](https://vimhelp.appspot.com/builtin.txt.html#getjumplist%28%29) function, instead of parsing the `:jumps` output.

I wonder how the structure would look like in the problematic case you've reported.

    :echo len(getjumplist()[0]) getjumplist()[1]

always has the first number smaller or at most equal (when there are no newer jumps and the last line of `:jumps` is just `>  `) than the second. If there's no `>` in `:jumps`, what's the second List element then??? If it's also equal to the number of elements of the first List, that could indicate that no `>` is the same as just `>   ` at the end (and that `:jumps` has a bug in omitting that output sometimes). If it's missing, `getjumplist()` is just as broken or mis-specified as `:jumps`.

So, if you'd have a chance to get the `getjumplist()` output when the plugin breaks down, that'd be great. Thank you (also for the good issue itself)!

**Comment by Konfekt** [comment]
Thank you for your prompt and kind reply. Here's an instance of the error message:

`:jumps` gives

```
 jump line  col file/text
   9    44    0 .git\rebase-merge\git-rebase-todo
   8    51    0 .git\rebase-merge\git-rebase-todo
   7   443    0 .git\rebase-merge\git-rebase-todo
   6   444    0 .git\rebase-merge\git-rebase-todo
   2     1    0 .git\COMMIT_EDITMSG
   1     1    0 .git\rebase-merge\git-rebase-todo
   2     2   42 let g:EnhancedJumps_CaptureJumpMessages = 0
```

`echo getjumplist()` gives

```
[[{'lnum': 44, 'bufnr': 4, 'col': 0, 'coladd': 0}, {'lnum': 51, 'bufnr': 4, 'col': 0, 'coladd': 0}, {'lnum': 443, 'bufnr': 4, 'col': 0, 'coladd': 0}, {'lnum': 444, 'bufnr': 4, 'col': 0, 'coladd': 0}, {'lnum': 1, 'bufnr': 1, 'col': 0, 'coladd': 0}, {'lnum': 2, 'bufnr': 1, 'col': 4, 'coladd': 0}, {'lnum': 4, 'bufnr': 1, 'col': 4, 'coladd': 0}, {'lnum': 1, 'bufnr': 3, 'col': 0, 'coladd': 0}, {'lnum': 1, 'bufnr': 4, 'col': 0, 'coladd': 0}, {'lnum': 1, 'bufnr': 14, 'col': 0, 'coladd': 0}, {'lnum': 2, 'bufnr': 14, 'col': 4, 'coladd': 0}, {'lnum': 2, 'bufnr': 2, 'col': 42, 'coladd': 0}], 9]
```

and `:echo len(getjumplist()[0]) getjumplist()[1]` gives `12 9`.

I wonder if it has to do with Vim `win32` getting confused about the file paths of Vim `win32unix` of Git on Windows and vice-versa. Edit: Probably not, since the same error occurs in Linux.

**Comment by inkarkat** [comment]
Oh, that's really interesting. Vim seems to get confused when rendering the jump list, but the internal data is not corrupted. (So if I changed the plugin to use `getjumplist()`, the problem should be gone.)

In your captured data, there should be 12 jump list entries, with the 10th being the current one; `:jumps` should therefore look like this:

```
 jump line  col file/text
   9    44    0 .git\rebase-merge\git-rebase-todo
   8    51    0 .git\rebase-merge\git-rebase-todo
   7   443    0 .git\rebase-merge\git-rebase-todo
   6   444    0 .git\rebase-merge\git-rebase-todo
   5     1    0 .git\COMMIT_EDITMSG
   4     2    4 .git\COMMIT_EDITMSG
   3     4    4 .git\COMMIT_EDITMSG
   2     1    0 "buffer3"
   1     1    0 .git\rebase-merge\git-rebase-todo
>  0     1    0 "buffer14"
   1     2    0 "buffer14"
   2     2   42 let g:EnhancedJumps_CaptureJumpMessages = 0
```

If the output looked like that, the plugin should work, too.

Two buffers (3 and 14) are somehow dropped from the output, and as the current jump position is in one, the `>` marker is missing, too.

---

Please report this Vim bug, see `:help bugs`. (Basically, open an issue at the [bug tracker](https://github.com/vim/vim/issues), or directly discuss this on the [vim_dev mailing list](https://www.vim.org/community.php).) You could directly reference this issue; [your reply](https://github.com/inkarkat/vim-EnhancedJumps/issues/6#issuecomment-1090229711) shows the problem pretty clearly.

I'll close this issue here, as I've tracked the switch to `getjumplist()` already elsewhere, and apart from that there's nothing else the plugin could do.

**Comment by Konfekt** [comment]
This issue was deferred to [Vim](https://github.com/vim/vim/issues/10100).
